# Generated by Django 5.2.8 on 2026-03-23 00:00

from django.db import migrations, models


def backfill_company_id(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    for profile in UserProfile.objects.select_related('user').all():
        if not profile.company_id:
            profile.company_id = profile.user.username
            profile.save(update_fields=['company_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(backfill_company_id, migrations.RunPython.noop),
    ]
