# Generated by Django 5.0.2 on 2026-02-05 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('MEMO', 'Memo')], max_length=20)),
                ('prefix', models.CharField(blank=True, max_length=50)),
                ('sequence', models.IntegerField(default=0)),
                ('ec_year', models.PositiveSmallIntegerField()),
                ('ref_no', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('receiver_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='REGISTERED', max_length=20)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('confidentiality', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.department')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='NumberingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbering_rules', to='core.department')),
            ],
            options={
                'verbose_name': 'Numbering Rule',
                'verbose_name_plural': 'Numbering Rules',
                'unique_together': {('department', 'doc_type')},
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20)),
                ('ec_year', models.PositiveSmallIntegerField()),
                ('current_value', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_sequences', to='core.department')),
            ],
            options={
                'unique_together': {('department', 'doc_type', 'ec_year')},
            },
        ),
    ]
