# Generated by Django 5.0.2 on 2026-02-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ceo_directed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ceo_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='co_offices',
            field=models.ManyToManyField(blank=True, related_name='co_office_documents', to='core.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='company_office_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='directed_offices',
            field=models.ManyToManyField(blank=True, related_name='directed_office_documents', to='core.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='memo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='signature_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='written_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
