# Generated by Django 5.2.8 on 2026-02-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_ceo_directed_date_document_ceo_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('EXTERNAL', 'External'), ('INTERNAL', 'Internal')], default='EXTERNAL', max_length=20),
        ),
    ]
