# Generated by Django 5.2.8 on 2026-02-07 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        ('documents', '0004_alter_document_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('DIRECTED', 'Directed'), ('DISPATCHED', 'Dispatched'), ('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='REGISTERED', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_acknowledgments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgments', to='core.department')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='documents.document')),
            ],
            options={
                'ordering': ['-acknowledged_at'],
                'unique_together': {('document', 'department')},
            },
        ),
    ]
