# Generated by Django 5.2.8 on 2026-02-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='confidentiality',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
    ]
