# Generated by Django 5.2.8 on 2026-02-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_confidentiality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='requires_ceo_direction',
            field=models.BooleanField(default=False),
        ),
    ]
