# Generated by Django 5.2.8 on 2026-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_requires_ceo_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cc_external_names',
            field=models.TextField(blank=True),
        ),
    ]
