# Generated by Django 5.2.8 on 2026-03-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        ('documents', '0009_document_cc_external_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cc_offices',
            field=models.ManyToManyField(blank=True, related_name='cc_office_documents', to='core.department'),
        ),
    ]
