# Generated by Django 5.2.8 on 2026-04-17 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_remove_ec_year_and_numbering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='letter_category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('REGULATORY', 'Regulatory')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='letter_type',
            field=models.CharField(choices=[('TECHNICAL', 'Technical'), ('LEGAL', 'Legal'), ('FINANCIAL', 'Financial'), ('ADMINISTRATIVE', 'Administrative'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.CreateModel(
            name='RegulatoryBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, unique=True)),
                ('name_am', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regulatory_bodies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='regulatory_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.regulatorybody'),
        ),
    ]
