# Generated by Django 5.2.8 on 2026-04-17 13:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_dispatched_at(apps, schema_editor):
    """Backfill dispatched_at from activity logs for existing documents"""
    Document = apps.get_model('documents', 'Document')
    Activity = apps.get_model('documents', 'Activity')
    
    # Get all documents that don't have dispatched_at set
    documents = Document.objects.filter(dispatched_at__isnull=True)
    
    updated_count = 0
    for doc in documents:
        # Find the first DISPATCHED activity
        activity = Activity.objects.filter(
            document=doc,
            action='Status changed to DISPATCHED'
        ).order_by('created_at').first()
        
        if activity:
            doc.dispatched_at = activity.created_at
            doc.save(update_fields=['dispatched_at'])
            updated_count += 1
    
    print(f"Backfilled dispatched_at for {updated_count} documents")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_add_user_id'),
        ('documents', '0012_document_letter_category_document_letter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when document status changed to DISPATCHED', null=True),
        ),
        migrations.RunPython(backfill_dispatched_at, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='DepartmentPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('metric_type', models.CharField(choices=[('receipt', 'Receipt Performance'), ('cc_acknowledgment', 'CC Acknowledgment Performance')], max_length=20)),
                ('average_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('document_count', models.IntegerField()),
                ('rank', models.IntegerField(help_text="Department's rank for that month")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='core.department')),
            ],
            options={
                'ordering': ['-month', 'rank'],
                'indexes': [models.Index(fields=['-month', 'metric_type'], name='documents_d_month_faa082_idx')],
                'unique_together': {('department', 'month', 'metric_type')},
            },
        ),
    ]
