# Generated by Django 4.2.7 on 2024-03-19 12:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tt_number', models.CharField(blank=True, help_text='Optional tracking number', max_length=50, null=True, unique=True)),
                ('arrival_date', models.DateField(help_text='Date letter arrived at CEO office')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('ETB', 'Ethiopian Birr'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='ETB', max_length=3)),
                ('payment_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('EXPENSE', 'Expense'), ('SALARY', 'Salary'), ('CONTRACT', 'Contract'), ('OTHER', 'Other')], max_length=20)),
                ('vendor_name', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('payment_date', models.DateField(help_text='Date of payment transaction')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ARRIVED', 'Arrived'), ('REGISTERED', 'Registered'), ('PENDING_CEO', 'Pending CEO'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='ARRIVED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('ceo_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_register_payment', 'Can register payment'), ('can_approve_payment', 'Can approve payment'), ('can_view_payment', 'Can view payment')],
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.payment')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
