# Generated by Django 5.0.2 on 2026-03-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_add_temp_ref_and_simplify_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'permissions': [('can_register_payment', 'Can register payment'), ('can_view_payment', 'Can view payment')]},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ceo_notes',
        ),
    ]
