# Generated by Django 5.2.8 on 2026-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_remove_payment_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='arrival_date',
            field=models.DateField(blank=True, help_text='Date letter arrived at CEO office', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date of payment transaction', null=True),
        ),
    ]
