# Generated by Django 5.2.8 on 2026-04-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_completed_by_payment_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='registry_date',
            field=models.DateField(blank=True, help_text='Date when registry number (ref_no) was issued', null=True),
        ),
    ]
